//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinebookshoppingbackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookTb()
        {
            this.OrderTbs = new HashSet<OrderTb>();
        }
    
        public int BookId { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public string BookDetail { get; set; }
        public Nullable<int> price { get; set; }
        public string BookCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTb> OrderTbs { get; set; }
    }
}
