//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinebookshoppingbackend
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onlinebookshoppingEntities : DbContext
    {
        public onlinebookshoppingEntities()
            : base("name=onlinebookshoppingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookTb> BookTbs { get; set; }
        public virtual DbSet<CartTb> CartTbs { get; set; }
        public virtual DbSet<OrderTb> OrderTbs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Tracking_detailsTb> Tracking_detailsTb { get; set; }
        public virtual DbSet<UserTb> UserTbs { get; set; }
    }
}
