//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlinebookshoppingbackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTb()
        {
            this.Tracking_detailsTb = new HashSet<Tracking_detailsTb>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> CartId { get; set; }
        public Nullable<int> payment { get; set; }
    
        public virtual BookTb BookTb { get; set; }
        public virtual CartTb CartTb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tracking_detailsTb> Tracking_detailsTb { get; set; }
    }
}
